// React_Js/elearning/src/Layouts/header.js
import React, { Component } from "react";
import { NavLink } from "react-router-dom";
import { connect } from "react-redux";

class Header extends Component {
  kiemTraStorage = () => {};

  render() {
    return (
      <div>
        <nav
          className="navbar navbar-expand-sm navbar-light"
          style={{ backgroundColor: "#e3f2fd" }}
        >
          <NavLink to="/" className="navbar-brand" href="#">
            Cyber Soft
          </NavLink>
          <button
            className="navbar-toggler d-lg-none"
            type="button"
            data-toggle="collapse"
            data-target="#collapsibleNavId"
            aria-controls="collapsibleNavId"
            aria-expanded="false"
            aria-label="Toggle navigation"
          />
          <div className="collapse navbar-collapse" id="collapsibleNavId">
            <ul className="navbar-nav mr-auto mt-2 mt-lg-0">
              <li className="nav-item active">
                <NavLink
                  to="/home"
                  className="nav-link"
                  activeClassName="bg-danger"
                  href="#"
                >
                  Home <span className="sr-only">(current)</span>
                </NavLink>
              </li>
              <li className="nav-item">
                <NavLink
                  to="/demohoc"
                  className="nav-link"
                  activeClassName="bg-danger"
                  href="#"
                >
                  Demo HOC
                </NavLink>
              </li>
            </ul>
            <ul className="navbar-nav">
              {this.props.credentials ? (
                <li className="nav-item">
                  <span className="nav-link text-danger">hello {this.props.credentials.hoTen} </span>
                </li>
              ) : (
                <li className="nav-item">
                  <NavLink
                    to="/login"
                    className="nav-link"
                    activeClassName="bg-danger"
                    href="#"
                  >
                    Login
                  </NavLink>
                </li>
              )}
            </ul>
          </div>
        </nav>
      </div>
    );
  }
}
const mapStateToProps = state => ({
  credentials: state.user.credentials
});
export default connect(mapStateToProps)(Header);

// AngularJs/Angularfe29/src/app/Movie-project/layout/header/header.component.ts
import { Component, OnInit } from "@angular/core";
import { UserServiceService } from "src/app/Services/user-service.service";

@Component({
  selector: "app-header",
  templateUrl: "./header.component.html",
  styleUrls: ["./header.component.scss"]
})
export class HeaderComponent implements OnInit {
  credentials: any;

  constructor(private _userService: UserServiceService) {}

  ngOnInit() {
    this.credentials = this._userService.credentials;
    this._userService.credentialsEmitter.subscribe(newCredentials => {
      this.credentials = newCredentials;
    });
  }
}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Movie</a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a routerLink="/" class="nav-link">Home</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <span class="nav-link" *ngIf="credentials; else authSection">Hi,{{credentials.hoTen}} </span>
      </li>
      <ng-template #authSection>
        <li class="nav-item">
          <a routerLink="/signin" class="nav-link text-danger">SignIn</a>
        </li>
        <li class="nav-item">
          <a routerLink="/signup" class="nav-link text-success">SignsUp</a>
        </li>
      </ng-template>
    </ul>
  </div>
</nav>
